# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.2.3
group=xyz.trivaxy.tia
java_version=21

# Common
minecraft_version=1.21.7
mod_name=Tiny Item Animations
mod_author=Trivaxy
mod_id=tia
license=LPUL
credits=
description=Adds a cute little animation when picking up items with your mouse.
minecraft_version_range_fabric=>=1.21.6
minecraft_version_range_neoforge=[1.21.6,)
homepage=https://modrinth.com/mod/tiny-item-animations
sources=https://github.com/trivaxy/tiny-item-animations

# Fabric
fabric_loader_version=0.16.14

# NeoForge
neoforge_version=21.7.25-beta
neoforge_loader_version_range=[2,)
neogradle_version=7.0.192

# Parchment
parchment_version=2025.07.18

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
